image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build

variables:
  DOCKER_DRIVER: overlay2

# Test simple
test:
  stage: test
  script:
    - echo "Test backend..."
    - test -f backend/app/main.py || (echo "main.py manquant" && exit 1)
    - test -f frontend/index.html || (echo "index.html manquant" && exit 1)
    - echo "Tests OK"

#  Build Docker
build:
  stage: build
  script:
    - docker build -t opsci-backend ./backend
    - docker build -t opsci-frontend ./frontend
    - echo "Build OK"