image: alpine:latest

stages:
  - test

test_files:
  stage: test
  script:
    - echo "Vérification des fichiers..."
    - test -f backend/app/main.py || (echo "backend/app/main.py manquant" && exit 1)
    - test -f frontend/index.html || (echo "frontend/index.html manquant" && exit 1)
    - test -f frontend/script.js || (echo "frontend/script.js manquant" && exit 1)
    - test -f frontend/style.css || (echo "frontend/style.css manquant" && exit 1)
    - echo "Tests OK"