services:
  db:
    image: postgres:16
    container_name: opsci-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: opsci-backend
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/movies_db
      TMDB_TOKEN: ${TMDB_TOKEN}
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: opsci-frontend
    depends_on:
      - backend
    environment :
      BACKEND_URL: http://localhost:8000
    ports:
      - "8080:8080"

  redis:
    image: redis:7
    container_name: opsci-redis
    ports:
      - "6379:6379"
volumes:
  postgres_data: