apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: opsci-backend:latest
          imagePullPolicy: Never
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: opsci-config
                  key: DATABASE_URL
            - name: TMDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: opsci-secret
                  key: TMDB_TOKEN
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000