apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: opsci-frontend:latest
          imagePullPolicy: Never
          env:
            - name: BACKEND_URL
              value: "http://127.0.0.1:41155"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      